[package]
name = "ckusro-core"
version = "0.0.1"
authors = ["tett23 <tett23@gmail.com>"]
edition = "2018"

[dependencies]
flate2 = { version = "^1.0.6", features = ["rust_backend"], default-features = false }
failure = { version = "^0.1.5" }
git2 = { version = "^0.8.0" }